plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'me.agradip'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

	implementation 'ch.qos.logback:logback-classic:1.5.17'
	implementation 'org.slf4j:slf4j-simple'

	implementation 'org.springframework.boot:spring-boot-starter-cache'

	implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'
	implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5'

	implementation 'org.ehcache:ehcache:3.10.8:jakarta'

	implementation 'org.springframework.boot:spring-boot-starter:3.4.3'
	implementation 'org.springframework.boot:spring-boot-starter-web:3.4.3'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.4.3'
	implementation 'org.springframework.security:spring-security-core:6.4.4'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-security:3.4.3'

	implementation 'com.zaxxer:HikariCP'
	implementation 'org.hibernate.orm:hibernate-core:6.6.8.Final'
	implementation 'org.hibernate:hibernate-community-dialects:6.1.7.Final'

	// SQLite
	implementation 'org.xerial:sqlite-jdbc:3.42.0.0'

	// MySQL / MariaDB
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

	// PostgreSQL
	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

import org.apache.tools.ant.taskdefs.condition.Os

//import java.nio.file.Paths
//
//def redocRepo = 'https://github.com/Redocly/redoc-cli.git'
//def redocDir = "${buildDir}/redoc"
//def redocDistDir = "${redocDir}/dist"
//def staticDir = "${projectDir}/src/main/resources/static"
//
//// Task to clone ReDoc if it’s not already cloned
//task cloneRedoc(type: Exec) {
//	doFirst {
//		println "Cloning ReDoc repository..."
//	}
//	commandLine 'git', 'clone', '--depth', '1', redocRepo, redocDir
//	onlyIf { !file(redocDir).exists() }
//}
//
//// Task to build ReDoc using npm
//task buildRedoc(type: Exec) {
//	dependsOn cloneRedoc
//	workingDir redocDir
//
//	doFirst {
//		println "Building ReDoc..."
//	}
//
//	if (Os.isFamily(Os.FAMILY_WINDOWS)) {
//		commandLine 'cmd', '/c', 'pnpm install && pnpm run build'
//	} else {
//		commandLine 'sh', '-c', 'pnpm install && pnpm run build'
//	}
//}
//
//// Task to copy built ReDoc files to Spring Boot's static directory
//task copyRedoc(type: Copy) {
//	dependsOn buildRedoc
//	from redocDistDir
//	into Paths.get(staticDir, "redoc")
//
//	doFirst {
//		println "Copying ReDoc to static directory..."
//	}
//}
//
//// Ensure ReDoc is built and copied before Spring Boot processes resources
//processResources.dependsOn copyRedoc
