spring.application.name=oxypaste

# Database
spring.datasource.url=jdbc:sqlite:oxypaste.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update

application.security.max-sessions=10
application.security.max-api-tokens=10

application.documents.readme=./documents/README.md
application.documents.license=./documents/LICENSE.md

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
