spring.application.name=oxypaste

# Database
spring.datasource.url=jdbc:sqlite:oxypaste.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update